package dev.dockerdashboard.ui

import androidx.compose.runtime.compositionLocalOf
import com.jakewharton.mosaic.ui.Color

data class Theme(
    val name: String,
    val accent: Color,
    val border: Color,
    val borderSelected: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textMuted: Color,
    val statusRunning: Color,
    val statusStopped: Color,
    val statusPaused: Color,
    val statusRestarting: Color,
    val statusCreated: Color,
    val barBackground: Color,
    val cardBackground: Color,
    val confirmBackground: Color,
    val searchBackground: Color,
    val updateAvailable: Color,
    val multiSelect: Color,
    val error: Color,
    val warning: Color,
    val sparklineCpu: Color,
    val sparklineMem: Color,
    val healthHealthy: Color,
    val healthUnhealthy: Color,
    val healthStarting: Color,
    val versionLocal: Color,
    val versionRemote: Color,
)

val DarkTheme = Theme(
    name = "Dark",
    accent = Color(80, 200, 255),
    border = Color(100, 100, 100),
    borderSelected = Color.Cyan,
    textPrimary = Color.White,
    textSecondary = Color(160, 160, 160),
    textMuted = Color(140, 140, 140),
    statusRunning = Color.Green,
    statusStopped = Color.Red,
    statusPaused = Color.Yellow,
    statusRestarting = Color.Cyan,
    statusCreated = Color.Blue,
    barBackground = Color(30, 30, 30),
    cardBackground = Color.Black,
    confirmBackground = Color(60, 30, 0),
    searchBackground = Color(20, 40, 60),
    updateAvailable = Color.Yellow,
    multiSelect = Color.Magenta,
    error = Color.Red,
    warning = Color.Yellow,
    sparklineCpu = Color.Cyan,
    sparklineMem = Color.Green,
    healthHealthy = Color.Green,
    healthUnhealthy = Color.Red,
    healthStarting = Color.Yellow,
    versionLocal = Color(100, 180, 255),
    versionRemote = Color.Green,
)

val LightTheme = Theme(
    name = "Light",
    accent = Color(0, 120, 200),
    border = Color(180, 180, 180),
    borderSelected = Color(0, 100, 180),
    textPrimary = Color.Black,
    textSecondary = Color(80, 80, 80),
    textMuted = Color(120, 120, 120),
    statusRunning = Color(0, 150, 0),
    statusStopped = Color(200, 0, 0),
    statusPaused = Color(180, 150, 0),
    statusRestarting = Color(0, 150, 180),
    statusCreated = Color(0, 0, 200),
    barBackground = Color(220, 220, 220),
    cardBackground = Color.White,
    confirmBackground = Color(255, 240, 200),
    searchBackground = Color(200, 230, 255),
    updateAvailable = Color(200, 150, 0),
    multiSelect = Color(180, 0, 180),
    error = Color(200, 0, 0),
    warning = Color(200, 150, 0),
    sparklineCpu = Color(0, 100, 180),
    sparklineMem = Color(0, 150, 0),
    healthHealthy = Color(0, 150, 0),
    healthUnhealthy = Color(200, 0, 0),
    healthStarting = Color(200, 150, 0),
    versionLocal = Color(0, 100, 180),
    versionRemote = Color(0, 150, 0),
)

val SolarizedTheme = Theme(
    name = "Solarized",
    accent = Color(38, 139, 210),
    border = Color(88, 110, 117),
    borderSelected = Color(38, 139, 210),
    textPrimary = Color(253, 246, 227),
    textSecondary = Color(147, 161, 161),
    textMuted = Color(88, 110, 117),
    statusRunning = Color(133, 153, 0),
    statusStopped = Color(220, 50, 47),
    statusPaused = Color(181, 137, 0),
    statusRestarting = Color(42, 161, 152),
    statusCreated = Color(38, 139, 210),
    barBackground = Color(0, 43, 54),
    cardBackground = Color(7, 54, 66),
    confirmBackground = Color(50, 50, 0),
    searchBackground = Color(0, 50, 70),
    updateAvailable = Color(181, 137, 0),
    multiSelect = Color(211, 54, 130),
    error = Color(220, 50, 47),
    warning = Color(181, 137, 0),
    sparklineCpu = Color(42, 161, 152),
    sparklineMem = Color(133, 153, 0),
    healthHealthy = Color(133, 153, 0),
    healthUnhealthy = Color(220, 50, 47),
    healthStarting = Color(181, 137, 0),
    versionLocal = Color(38, 139, 210),
    versionRemote = Color(133, 153, 0),
)

val allThemes = listOf(DarkTheme, LightTheme, SolarizedTheme)

val LocalTheme = compositionLocalOf { DarkTheme }
